[translation]
# API根地址
URL = "https://openapi.youdao.com"
# API路径地址
URL_PATH = "/api"
# 您的应用ID
APP_KEY = "4640c2e2f0acce5e"
# 您的应用密钥
APP_SECRET = "fVOM1n2P2OtznRJHynKMaZgtD5JHXe6B"
# 源语言
FROM = "auto"
# 目标语言 https://ai.youdao.com/DOCSIRMA/html/trans/api/wbfy/index.html
TO = "zh-CHS"

[setting]
# 是否深层目录 仅目录生效
DEEP = true
# 目标范围，文件=files\目录=dirs\所有=all
TARGET = "dirs"
# 是否规范命名
SPECIFICATION = true
# 命名分割字符
# ❗ 注意若目录名原先存在分割字符，会只保留分割部分
SPACER_CHARACTER = " "

[concurrency]
# 最大线程数
MAX_THREAD = 1
# 最大协程数
MAX_COROUTINE = 1
# 并发延迟，应对有道API该死的频率限制
DELAY = 0.8

[log]
# 是否启用日志
ENABLE = false
